INSERT INTO ACAO (ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (BOT_ACAO_SEQ.NEXTVAL,'atualizacao de sistema','verifica na internet possiveis atualizacoes de sistema', true)
INSERT INTO ACAO (ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (BOT_ACAO_SEQ.NEXTVAL,'Identificar erros','identifica se possui erros', true)
INSERT INTO ACAO (ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (BOT_ACAO_SEQ.NEXTVAL,'Transferência de consciencia','transfere a consciência para outro robô', true)

INSERT INTO EXECUCAO (ID_EXECUCAO, ID_ACAO, DATA_EXECUCAO) VALUES (BOT_EXECUCAO_SEQ.NEXTVAL,1,SYSDATE);
INSERT INTO EXECUCAO (ID_EXECUCAO, ID_ACAO, DATA_EXECUCAO) VALUES (BOT_EXECUCAO_SEQ.NEXTVAL,2,'2020-11-12T02:37:16.134Z');
INSERT INTO EXECUCAO (ID_EXECUCAO, ID_ACAO, DATA_EXECUCAO) VALUES (BOT_EXECUCAO_SEQ.NEXTVAL,1,SYSDATE);